# Generated by Django 2.0.6 on 2018-06-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
