# Generated by Django 2.0.7 on 2018-07-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20180731_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='url',
            field=models.URLField(),
        ),
    ]
