# Generated by Django 2.0.6 on 2018-06-26 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20180626_1613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
